
[global_env]

[scripts]
dev = "cargo run"
build = { command = "cargo build", env = { RUST_LOG = "info" } }
release = "cargo build --release"
# test = { command = "cargo test", env = { RUST_LOG = "warn" } }
doc = "cargo doc --no-deps --open"
sqlx = 'cargo sqlx prepare --database-url "sqlite:movies.db" -- --tests'
test = "cargo test -- --nocapture"
